name: Scala Docker Image and Deploy

on:
  push:
    branches:
      - main

env:
  GOOGLE_APPLICATION_CREDENTIALS: ${{ secrets.GOOGLE_APPLICATION_CREDENTIALS }}
  ARTIFACT_REPOSITORY_URL: gcr.io/us-docker.pkg.dev/trans-sunset-370818
  API_IMAGE_NAME: drugscraper/api
  API_IMAGE_TAG: latest

jobs:
  build and upload scrape-api:
    needs: terraform_apply_artifact_repository
    permissions:
      contents: 'read'
      id-token: 'write'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up JDK
        uses: actions/setup-java@v3.10.0
        with:
          java-version: 17
          distribution: oracle

      - name: Set up Scala
        uses: olafurpg/setup-scala@v10
        with:
          scala-version: 2.13.10

      - name: Assemble Scala application
        run: sbt assembly
        working-directory: scrape-api

      - name: Authenticate with Google Cloud
        uses: google-github-actions/auth@v1
        with:
          workload_identity_provider: ${{ secrets.WIF_POOL }}
          service_account: ${{ secrets.SA_EMAIL }}

      - name: Build and push image to artifact repository
        uses: docker/build-push-action@v2
        with:
          context: scrape-api
          push: true
          tags: ${{ env.ARTIFACT_REPOSITORY_URL }}/${{ env.API_IMAGE_NAME }}:${{ env.API_IMAGE_TAG }}
      
    


