name: Scala Docker Image and Deploy

on:
  push:
    branches:
      - main

env:
  GCR_REGISTRY: gcr.io/us-docker.pkg.dev/drugscraper-project
  IMAGE_NAME: drugscraper/api
  TAG: latest

jobs:
  build:
    permissions:
      contents: 'read'
      id-token: 'write'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up JDK
        uses: actions/setup-java@v3.10.0
        with:
          java-version: 17
          distribution: oracle

      - name: Set up Scala
        uses: olafurpg/setup-scala@v10
        with:
          scala-version: 2.13.10

      - name: Assemble Scala application
        run: sbt assembly

      - name: Authenticate with Google Cloud
        uses: google-github-actions/auth@v1
        with:
          workload_identity_provider: ${{ secrets.WIF_POOL }}
          service_account: ${{ secrets.SA_EMAIL }}

      - name: Build Docker Image
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: ${{ env.GCR_REGISTRY }}/${{ env.IMAGE_NAME }}:${{ env.TAG }}
      
    


