name: Terraform apply

on:
  push:
    branches:
      - main

jobs:
  terraform_apply:
    permissions:
      contents: 'read'
      id-token: 'write'
    runs-on: ubuntu-latest
    steps:
      - name: checkout code
        uses: actions/checkout@v2

      - name: setup terraform
        uses: hashicorp/setup-terraform@v1
        with:
          terraform_version: 0.17.0

      - name: terraform fmt
        run: terraform fmt
        with:
          working-directory: orchestration

      - name: terraform init
        run: terraform init
        with:
          working-directory: orchestration

      - name: terraform validate
        run: terraform validate
        with:
          working-directory: orchestration

      - name: terraform apply
        run: terraform apply
        with:
          working-directory: orchestration

