name: Terraform apply

on:
  push:
    branches:
      - main

jobs:
  terraform_apply:
    permissions:
      contents: 'read'
      id-token: 'write'
    runs-on: ubuntu-latest
    steps:
      - name: checkout code
        uses: actions/checkout@v2

      - name: HashiCorp - Setup Terraform
        uses: hashicorp/setup-terraform@v2.0.3


      - name: terraform fmt
        run: terraform fmt
        working-directory: orchestration

      - name: terraform init
        run: terraform init -upgrade
        working-directory: orchestration

      - name: terraform validate
        run: terraform validate
        working-directory: orchestration

      - name: terraform apply
        run: terraform apply
        working-directory: orchestration

